apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rustcost.fullname" . }}-core-deploy
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rustcost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustcost.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rustcost.fullname" . }}-sa

      securityContext:
        fsGroup: 1000

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}

          env:
            - name: NODE_EXPORTER_URLS
              value: "http://{{ include "rustcost.fullname" . }}-node-exporter:{{ .Values.nodeExporter.port }}/metrics"

            {{- if .Values.cadvisor.enabled }}
            - name: CADVISOR_URLS
              value: "http://{{ default (printf "%s-cadvisor" (include "rustcost.fullname" .)) .Values.cadvisor.serviceName }}:{{ .Values.cadvisor.port }}/metrics"
            {{- end }}

            - name: RUST_LOG
              value: {{ include "rustcost.rustlog" . | quote }}

            - name: HOST
              value: "0.0.0.0"

          volumeMounts:
            - name: data
              mountPath: /app/data

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rustcost.fullname" . }}-pvc
